import { Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import {
  User,
  UserSchema,
  Category,
  CategorySchema,
  Brand,
  BrandSchema,
  Inventory,
  InventorySchema,
  Product,
  ProductSchema,
  Cart,
  CartSchema,
  Wishlist,
  WishlistSchema,
  Coupon,
  CouponSchema,
  Order,
  OrderSchema,
  Payment,
  PaymentSchema,
  Review,
  ReviewSchema,
  Ticket,
  TicketSchema,
  Notification,
  NotificationSchema,
  Log,
  LogSchema,
  Vendor,
  VendorSchema,
  Settlement,
  SettlementSchema,
  Analytics,
  AnalyticsSchema,
  Address,
  AddressSchema,
  PaymentMethod,
  PaymentMethodSchema,
  WalletTransaction,
  WalletTransactionSchema,
  Referral,
  ReferralSchema,
  RefundTransaction,
  RefundTransactionSchema,
  PaymentAuditLog,
  PaymentAuditLogSchema,
  PaymentWebhookLog,
  PaymentWebhookLogSchema,
  AgentStatus,
  AgentStatusSchema,
  LiveChatSession,
  LiveChatSessionSchema,
  LedgerEntry,
  LedgerEntrySchema,
  Warehouse,
  WarehouseSchema,
  FileMetadata,
  FileMetadataSchema,
  AdminSession,
  AdminSessionSchema,
  SystemSetting,
  SystemSettingSchema,
  AuditLog,
  AuditLogSchema,
  SearchLog,
  SearchLogSchema,
  ActivityLog,
  ActivityLogSchema,
  ChatbotLog,
  ChatbotLogSchema,
  AnalyticsCache,
  AnalyticsCacheSchema,
  ApiLog,
  ApiLogSchema,
  SecurityLog,
  SecurityLogSchema,
  LoginLog,
  LoginLogSchema,
  ImportLog,
  ImportLogSchema,
  ExportLog,
  ExportLogSchema,
  GuestLog,
  GuestLogSchema,
  ChangeHistory,
  ChangeHistorySchema,
  FeedbackTicket,
  FeedbackTicketSchema,
  FeedbackComment,
  FeedbackCommentSchema,
  FeedbackAttachment,
  FeedbackAttachmentSchema,
  FeedbackVote,
  FeedbackVoteSchema,
  FeedbackActivityLog,
  FeedbackActivityLogSchema,
} from './schemas';

@Module({
  imports: [
    MongooseModule.forFeature([
      { name: User.name, schema: UserSchema },
      { name: Category.name, schema: CategorySchema },
      { name: Brand.name, schema: BrandSchema },
      { name: Inventory.name, schema: InventorySchema },
      { name: Product.name, schema: ProductSchema },
      { name: Cart.name, schema: CartSchema },
      { name: Wishlist.name, schema: WishlistSchema },
      { name: Coupon.name, schema: CouponSchema },
      { name: Order.name, schema: OrderSchema },
      { name: Payment.name, schema: PaymentSchema },
      { name: Review.name, schema: ReviewSchema },
      { name: Ticket.name, schema: TicketSchema },
      { name: Notification.name, schema: NotificationSchema },
      { name: Log.name, schema: LogSchema },
      { name: Vendor.name, schema: VendorSchema },
      { name: Settlement.name, schema: SettlementSchema },
      { name: Analytics.name, schema: AnalyticsSchema },
      { name: Address.name, schema: AddressSchema },
      { name: PaymentMethod.name, schema: PaymentMethodSchema },
      { name: WalletTransaction.name, schema: WalletTransactionSchema },
      { name: Referral.name, schema: ReferralSchema },
      { name: RefundTransaction.name, schema: RefundTransactionSchema },
      { name: PaymentAuditLog.name, schema: PaymentAuditLogSchema },
      { name: PaymentWebhookLog.name, schema: PaymentWebhookLogSchema },
      { name: AgentStatus.name, schema: AgentStatusSchema },
      { name: LiveChatSession.name, schema: LiveChatSessionSchema },
      { name: LedgerEntry.name, schema: LedgerEntrySchema },
      { name: Warehouse.name, schema: WarehouseSchema },
      { name: FileMetadata.name, schema: FileMetadataSchema },
      { name: AdminSession.name, schema: AdminSessionSchema },
      { name: SystemSetting.name, schema: SystemSettingSchema },
      { name: AuditLog.name, schema: AuditLogSchema },
      { name: SearchLog.name, schema: SearchLogSchema },
      { name: ActivityLog.name, schema: ActivityLogSchema },
      { name: ChatbotLog.name, schema: ChatbotLogSchema },
      { name: AnalyticsCache.name, schema: AnalyticsCacheSchema },
      { name: ApiLog.name, schema: ApiLogSchema },
      { name: SecurityLog.name, schema: SecurityLogSchema },
      { name: LoginLog.name, schema: LoginLogSchema },
      { name: ImportLog.name, schema: ImportLogSchema },
      { name: ExportLog.name, schema: ExportLogSchema },
      { name: GuestLog.name, schema: GuestLogSchema },
      { name: ChangeHistory.name, schema: ChangeHistorySchema },
      { name: FeedbackTicket.name, schema: FeedbackTicketSchema },
      { name: FeedbackComment.name, schema: FeedbackCommentSchema },
      { name: FeedbackAttachment.name, schema: FeedbackAttachmentSchema },
      { name: FeedbackVote.name, schema: FeedbackVoteSchema },
      { name: FeedbackActivityLog.name, schema: FeedbackActivityLogSchema },
    ]),
  ],
  exports: [MongooseModule],
})
export class SchemasModule {}


